Add haddock generation

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -74,6 +74,31 @@ jobs:
       - name: Generate package dist
         run: cabal sdist
 
+      - name: Generate Haddock
+        shell: bash
+        # We're doing it in such a complicated way to work around a bug in Cabal,
+        # due to which it may generate documentation dist only for the internal libs,
+        # if the name of the package is not specified thus:
+        # `cabal haddock --haddock-for-hackage $package_name`.
+        run: |
+          cabal_file=$(find . -maxdepth 1 -name "*.cabal" -print -quit)
+          if [ ! -f "$cabal_file" ]; then
+            echo "Cabal-file not found"
+            exit 1
+          fi
+
+          package_name=$(awk -F ":[[:space:]]*" 'tolower($1)=="name"    { print $2 }' < "$cabal_file")
+          if [ -z "$package_name" ]; then
+            echo "Unable to determine package name"
+            exit 1
+          fi
+
+          echo "Determined package name: $package_name"
+
+          cabal update
+          { file=$(cabal haddock --haddock-for-hackage $package_name | tee /dev/fd/3 | tail -1); } 3>&1
+          echo "file=${file}" >> "${GITHUB_OUTPUT}"
+
       - name: Publish on Hackage
         uses: haskell-actions/hackage-publish@v1.1
         with:
